export interface ListaCamara {
  nombre: string;
  logo: string;
  preferente: boolean;
  elegido: boolean;
  candidatos: Array<{ numero: number; elegido: boolean }>;
}

export const LISTAS_CAMARA: ListaCamara[] = [
  {
    nombre: 'CIUDADANOS RENOVEMOS',
    logo: 'assets/images/ciudadanos-renovemos.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'PARTIDO LIBERAL COLOMBIANO',
    logo: 'assets/images/partido-liberal.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'CR-LA U OXÍGENO – CJL-LA LIGA-ASL',
    logo: 'assets/images/oxigeno-liga.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'MOVIMIENTO SALVACIÓN NACIONAL',
    logo: 'assets/images/salvacion-nacional.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'MIRA + DIGNIDAD Y COMPROMISO',
    logo: 'assets/images/mira-dignidad.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'MOTOCICLISTAS Y CONDUCTORES UNIDOS POR LA CAUSA',
    logo: 'assets/images/motociclistas.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA – AICO',
    logo: 'assets/images/aico.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'PARTIDO ALIANZA VERDE',
    logo: 'assets/images/alianza-verde.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'PARTIDO CONSERVADOR COLOMBIANO',
    logo: 'assets/images/partido-conservador.png',
    preferente: true,
    elegido: true,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: true },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'PACTO HISTÓRICO BOGOTÁ',
    logo: 'assets/images/pacto-historico.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'ABC ALIANZA BOGOTÁ CONVERGENTE',
    logo: 'assets/images/abc-alianza.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'CON TODA POR BOGOTÁ',
    logo: 'assets/images/con-toda-bogota.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'PARTIDO CENTRO DEMOCRÁTICO',
    logo: 'assets/images/centro-democratico.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'NUESTRA FUERZA',
    logo: 'assets/images/nuestra-fuerza.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'PARTIDO NUEVO LIBERALISMO',
    logo: 'assets/images/nuevo-liberalismo.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 101, elegido: false },
      { numero: 102, elegido: false },
      { numero: 103, elegido: false },
      { numero: 104, elegido: false },
      { numero: 105, elegido: false },
      { numero: 106, elegido: false },
      { numero: 107, elegido: false },
      { numero: 108, elegido: false },
      { numero: 109, elegido: false },
      { numero: 110, elegido: false },
      { numero: 111, elegido: false },
      { numero: 112, elegido: false },
      { numero: 113, elegido: false },
      { numero: 114, elegido: false },
      { numero: 115, elegido: false },
      { numero: 116, elegido: false },
      { numero: 117, elegido: false },
      { numero: 118, elegido: false },
    ],
  },
  {
    nombre: 'VOTO EN BLANCO',
    logo: 'assets/images/voto-blanco.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
];
