export interface ListaSenado {
  nombre: string;
  logo: string;
  preferente: boolean;
  elegido: boolean;
  candidatos: Array<{ numero: number; elegido: boolean }>;
}

export const LISTAS_SENADO: ListaSenado[] = [
  {
    nombre: 'PARTIDO DE LA UNIÓN POR LA GENTE - PARTIDO DE LA U',
    logo: 'assets/images/partido-u.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 65, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 71, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 81, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 89, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'COALICIÓN FUERZA CIUDADANA',
    logo: 'assets/images/fuerza-ciudadana.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 85, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'PARTIDO CENTRO DEMOCRÁTICO',
    logo: 'assets/images/centro-democratico.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },

  {
    nombre: 'PACTO HISTÓRICO SENADO',
    logo: 'assets/images/pacto-historico.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'PARTIDO CONSERVADOR COLOMBIANO',
    logo: 'assets/images/partido-conservador.png',
    preferente: true,
    elegido: true,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: true },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 65, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 81, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 89, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },

  {
    nombre: 'PARTIDO POLÍTICO OXÍGENO',
    logo: 'assets/images/oxigeno.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },

  {
    nombre: 'PATRIOTAS',
    logo: 'assets/images/patriotas.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'LA LISTA DE OVIEDO - CON TODA POR COLOMBIA',
    logo: 'assets/images/lista-oviedo.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'COALICIÓN CAMBIO RADICAL - ALMA',
    logo: 'assets/images/cambio-radical-alma.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 65, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 71, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 81, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 89, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'ALIANZA POR COLOMBIA',
    logo: 'assets/images/alianza-verde.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 65, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 71, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 81, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 89, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'CREEMOS',
    logo: 'assets/images/creemos.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
    ],
  },
  {
    nombre: 'MOVIMIENTO SALVACIÓN NACIONAL',
    logo: 'assets/images/salvacion-nacional.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 55, elegido: false },
      { numero: 60, elegido: false },
      { numero: 70, elegido: false },
      { numero: 72, elegido: false },
      { numero: 75, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 80, elegido: false },
      { numero: 85, elegido: false },
      { numero: 88, elegido: false },
      { numero: 90, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'COLOMBIA SEGURA Y PRÓSPERA',
    logo: 'assets/images/colombia-segura-prospera.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
  {
    nombre: 'AHORA COLOMBIA',
    logo: 'assets/images/ahora-colombia.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 65, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 71, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 81, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'FRENTE AMPLIO UNITARIO',
    logo: 'assets/images/frente-amplio.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 71, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 89, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },

  {
    nombre: 'PARTIDO LIBERAL COLOMBIANO',
    logo: 'assets/images/partido-liberal.png',
    preferente: true,
    elegido: false,
    candidatos: [
      { numero: 1, elegido: false },
      { numero: 2, elegido: false },
      { numero: 3, elegido: false },
      { numero: 4, elegido: false },
      { numero: 5, elegido: false },
      { numero: 6, elegido: false },
      { numero: 7, elegido: false },
      { numero: 8, elegido: false },
      { numero: 9, elegido: false },
      { numero: 10, elegido: false },
      { numero: 11, elegido: false },
      { numero: 12, elegido: false },
      { numero: 13, elegido: false },
      { numero: 14, elegido: false },
      { numero: 15, elegido: false },
      { numero: 16, elegido: false },
      { numero: 17, elegido: false },
      { numero: 18, elegido: false },
      { numero: 19, elegido: false },
      { numero: 20, elegido: false },
      { numero: 21, elegido: false },
      { numero: 22, elegido: false },
      { numero: 23, elegido: false },
      { numero: 24, elegido: false },
      { numero: 25, elegido: false },
      { numero: 26, elegido: false },
      { numero: 27, elegido: false },
      { numero: 28, elegido: false },
      { numero: 29, elegido: false },
      { numero: 30, elegido: false },
      { numero: 31, elegido: false },
      { numero: 32, elegido: false },
      { numero: 33, elegido: false },
      { numero: 34, elegido: false },
      { numero: 35, elegido: false },
      { numero: 36, elegido: false },
      { numero: 37, elegido: false },
      { numero: 38, elegido: false },
      { numero: 39, elegido: false },
      { numero: 40, elegido: false },
      { numero: 41, elegido: false },
      { numero: 42, elegido: false },
      { numero: 43, elegido: false },
      { numero: 44, elegido: false },
      { numero: 45, elegido: false },
      { numero: 46, elegido: false },
      { numero: 47, elegido: false },
      { numero: 48, elegido: false },
      { numero: 49, elegido: false },
      { numero: 50, elegido: false },
      { numero: 51, elegido: false },
      { numero: 52, elegido: false },
      { numero: 53, elegido: false },
      { numero: 54, elegido: false },
      { numero: 55, elegido: false },
      { numero: 56, elegido: false },
      { numero: 57, elegido: false },
      { numero: 58, elegido: false },
      { numero: 59, elegido: false },
      { numero: 60, elegido: false },
      { numero: 61, elegido: false },
      { numero: 62, elegido: false },
      { numero: 63, elegido: false },
      { numero: 64, elegido: false },
      { numero: 65, elegido: false },
      { numero: 66, elegido: false },
      { numero: 67, elegido: false },
      { numero: 68, elegido: false },
      { numero: 69, elegido: false },
      { numero: 70, elegido: false },
      { numero: 71, elegido: false },
      { numero: 72, elegido: false },
      { numero: 73, elegido: false },
      { numero: 74, elegido: false },
      { numero: 75, elegido: false },
      { numero: 76, elegido: false },
      { numero: 77, elegido: false },
      { numero: 78, elegido: false },
      { numero: 79, elegido: false },
      { numero: 80, elegido: false },
      { numero: 81, elegido: false },
      { numero: 82, elegido: false },
      { numero: 83, elegido: false },
      { numero: 84, elegido: false },
      { numero: 85, elegido: false },
      { numero: 86, elegido: false },
      { numero: 87, elegido: false },
      { numero: 88, elegido: false },
      { numero: 89, elegido: false },
      { numero: 90, elegido: false },
      { numero: 91, elegido: false },
      { numero: 92, elegido: false },
      { numero: 93, elegido: false },
      { numero: 94, elegido: false },
      { numero: 95, elegido: false },
      { numero: 96, elegido: false },
      { numero: 97, elegido: false },
      { numero: 98, elegido: false },
      { numero: 99, elegido: false },
      { numero: 100, elegido: false },
    ],
  },
  {
    nombre: 'VOTO EN BLANCO',
    logo: 'assets/images/voto-blanco.png',
    preferente: false,
    elegido: false,
    candidatos: [],
  },
];
